version: '2'
services:
  web:
#Builds web service from image specified in the "." Dockerfile 
    build: .
#Binds local port to container port
    ports:
      - "5000:5000"
    env_file: .env
#Builds db container first
#    depends_on:
#      - db
#Mounts container volume
    volumes:
      - ./webapp:/opt/webapp
#Builds database service using mongo image from dockerhub
#  db:
#    image: mongo:latest
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: rootpassword
#Binds local port to container port
#    ports:
#      - 27017:27017
#Mounts container volume  
   # volumes:
    #'  - mongodb_data_container:/data/db

  #volumes:
   #  mongodb_data_container:
 # redis:
 #   image: redis:alpine
 #   ports:
 #      - "6379:6379"
